# Pandas - Data Wrangling

## References Books, Sties and Online Tutorials

- [Brace, L.](https://exeter-qstep-resources.github.io/Q-Step_WS_06112019_Data_Analysis_and_visualisation_with_Python.pptx) 2019. Data Analysis and Visualisation with Python. Q-Step Workshop
- [Feldman, J.](http://jake-feldman.squarespace.com/data-science-python-oscm400c) Data Science - Python
- [Beuzen, T.](https://www.tomasbeuzen.com/python-programming-for-data-science/chapters/chapter8-wrangling-basics.html) Python Programming for Data Science

***

<font size="5">**Learning Objectives**</font><br>
<font size="3">After this session, you should be able to:</font>
- <font size="3">use built-in methods to analyse data on dataframe</font>
- <font size="3">manipulate dataset using pandas package: filter, groupby, sorting, create a new column, delete a column</font>

***

# Basic statistic using built-in methods

In [2]:
import pandas as pd
file_path = "Data/apple_stock_data.csv"

try:
    #Read in the data frame
    stock_df=pd.read_csv(file_path, header=0, encoding='utf-8')
except FileNotFoundError as e1:
    print(f"File not found - {e1}")
except Exception as e2:
    print(f"Exception - {e2}")

## sum() - return the sum of the values over the requested axis

In [3]:
# Compute sum of stock price at the closing of the trading day
stock_df['Close'].sum()

np.float64(24269.859941)

In [4]:
# Compute sum of stock price at the opening and the closing for every rows: 
# Axis = 0 is by default and it's for the rows while axis = 1 is for the cols.
open_close_price = stock_df[['Open','Close']].sum(axis=1)

open_close_price

0      231.950005
1      231.869995
2      232.529999
3      234.690003
4      236.939995
          ...
164    321.610000
165    323.010010
166    327.150009
167    327.639999
168    328.850006
Length: 169, dtype: float64

## eval() - evaluate a string describing operations on DataFrame columns

In [5]:
stock_df.eval('Open+Close')

0      231.950005
1      231.869995
2      232.529999
3      234.690003
4      236.939995
          ...
164    321.610000
165    323.010010
166    327.150009
167    327.639999
168    328.850006
Length: 169, dtype: float64

## max() - return the maximum of the values over the requested axis

In [6]:
# Compute the highest number of shares traded during the trading day
max_volume = stock_df['Volume'].max()

print(f"Max number of shares traded: {max_volume:,}")

Max number of shares traded: 111,985,000

## min() - return the minimum of the values over the requested axis

In [7]:
# Compute the lowest of maximum stock price during the trading day
min_high_price = stock_df['High'].min()

print(f"Minimum of Maximum stock price: ${min_high_price:,.2f}")

Minimum of Maximum stock price: $116.33

## mean() - return the mean of the values over the requested axis

In [8]:
# Compute mean of maximum and minimum stock price during the trading day
mean_high_low_price = stock_df[['High','Low']].mean()

print(f"Mean of Maximum and Minimum stock price:\n{mean_high_low_price}")

Mean of Maximum and Minimum stock price:
High    144.389704
Low     142.612840
dtype: float64

## std() - return sample standard deviation over requested axis

In [9]:
# Compute standard deviation of stock price at the closing of the trading day
std_close = stock_df['Close'].std()

print(f"Standard deviation of stock price at the closing of the trading day: {std_close:.2f}")

Standard deviation of stock price at the closing of the trading day: 11.78

## describe() - generate descriptive statistics

In [10]:
# Compute key stats for every numeric column
summary = stock_df.describe()
summary

,Open,High,Low,Close,Adj Close,Volume
count,169.000000,169.000000,169.000000,169.000000,169.000000,1.690000e+02
mean,143.465799,144.389704,142.612840,143.608639,142.225634,2.668999e+07
std,11.959822,12.021139,11.667212,11.780166,12.108588,1.139126e+07
min,115.800003,116.330002,114.760002,116.019997,114.183815,1.424630e+07
25%,138.850006,139.649994,138.600006,139.000000,137.393234,2.034630e+07
50%,144.190002,144.899994,143.309998,144.089996,142.859299,2.379350e+07
75%,153.419998,153.990005,152.220001,153.059998,151.617416,2.878190e+07
max,164.800003,164.940002,163.630005,164.050003,163.462372,1.119850e+08

In [11]:
# We can index and slice the above dataframe like any other dataframe.
summary.loc[['min', 'max'], ['Open', 'Close']]

           Open       Close
min  115.800003  116.019997
max  164.800003  164.050003

----

# Data Wrangling

<font size=3>A data wrangling process, also known as a data munging process, consists of reorganising, transforming and mapping data from one "raw" form into another in order to make it more usable and valuable for a variety of downstream uses including analytics.</font>

##  to_datetime(arg, format) - converts a Python object to datetime format
Where, format is a string representing the type of required date format. 
For year %y, For month %m, For day %d

- passing `format='ISO8601'` if your strings are all [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) but not necessarily in exactly the same format;
- passing `format='mixed'`, and the format will be inferred for each element individually. This is risky, and you should probably use it along with `dayfirst=True`.
- see [strftime documentation](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior) for more information on choice.

In [12]:
stock_df['Date'] = pd.to_datetime(stock_df['Date'],format="%d-%m-%y")
stock_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday
0,2017-01-03,115.800003,116.330002,114.760002,116.150002,114.311760,28781900,Jan,Tuesday
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,114.183815,21118100,Jan,Wednesday
2,2017-01-05,115.919998,116.860001,115.809998,116.610001,114.764473,22193600,Jan,Thursday
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday

- <font>Converting data to datetime type in pandas allows for operations like calculating time differences and grouping by time units (e.g., year, month, day), which can't be done with string data. This enables more efficient time-based analysis and manipulation.</font>
- <font>You can extract the day, month, and year from the datetime objects using the .dt attribute:</font>
    - <font>dt.day - attribute to get the day.</font>
    - <font>dt.month - attribute to get the month.</font>
    - <font>dt.year - attribute to get the year.</font>

In [13]:
stock_df['Date'].dt.day

0       3
1       4
2       5
3       6
4       9
       ..
164    28
165    29
166    30
167    31
168     1
Name: Date, Length: 169, dtype: int32

In [14]:
stock_df['Date'].dt.month

0      1
1      1
2      1
3      1
4      1
      ..
164    8
165    8
166    8
167    8
168    9
Name: Date, Length: 169, dtype: int32

In [15]:
stock_df['Date'].dt.year

0      2017
1      2017
2      2017
3      2017
4      2017
       ...
164    2017
165    2017
166    2017
167    2017
168    2017
Name: Date, Length: 169, dtype: int32

In [16]:
# Filter DataFrame for rows from February (month = 2)
filtered_df = stock_df.loc[stock_df['Date'].dt.month == 2]
filtered_df

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday
20,2017-02-01,127.029999,130.490005,127.010002,128.750000,126.712341,111985000,Feb,Wednesday
21,2017-02-02,127.980003,129.389999,127.779999,128.529999,126.495819,33710400,Feb,Thursday
22,2017-02-03,128.309998,129.190002,128.160004,129.080002,127.037125,24507300,Feb,Friday
23,2017-02-06,129.130005,130.500000,128.899994,130.289993,128.227966,26845900,Feb,Monday
24,2017-02-07,130.539993,132.089996,130.449997,131.529999,129.448349,38183800,Feb,Tuesday
25,2017-02-08,131.350006,132.220001,131.220001,132.039993,129.950287,23004100,Feb,Wednesday
26,2017-02-09,131.649994,132.449997,131.119995,132.419998,130.889282,28349900,Feb,Thursday
27,2017-02-10,132.460007,132.940002,132.050003,132.119995,130.592758,20065500,Feb,Friday
28,2017-02-13,133.080002,133.820007,132.750000,133.289993,131.749222,23035400,Feb,Monday
29,2017-02-14,133.470001,135.089996,133.250000,135.020004,133.459244,33226200,Feb,Tuesday
30,2017-02-15,135.520004,136.270004,134.619995,135.509995,133.943573,35623100,Feb,Wednesday
31,2017-02-16,135.669998,135.899994,134.839996,135.350006,133.785416,22584600,Feb,Thursday
32,2017-02-17,135.100006,135.830002,135.100006,135.720001,134.151154,22198200,Feb,Friday
33,2017-02-21,136.229996,136.750000,135.979996,136.699997,135.119827,24507200,Feb,Tuesday
34,2017-02-22,136.429993,137.119995,136.110001,137.110001,135.525070,20836900,Feb,Wednesday
35,2017-02-23,137.380005,137.479996,136.300003,136.529999,134.951782,20788200,Feb,Thursday
36,2017-02-24,135.910004,136.660004,135.279999,136.660004,135.080292,21776600,Feb,Friday
37,2017-02-27,137.139999,137.440002,136.279999,136.929993,135.347153,20257400,Feb,Monday
38,2017-02-28,137.080002,137.440002,136.699997,136.990005,135.406479,23482900,Feb,Tuesday

## Create new columns

In [17]:
# Create a new column to store total sale price of a day
stock_df['Total_sale'] = stock_df[['Open','Close']].sum(axis=1)

In [18]:
stock_df

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Total_sale
0,2017-01-03,115.800003,116.330002,114.760002,116.150002,114.311760,28781900,Jan,Tuesday,231.950005
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,114.183815,21118100,Jan,Wednesday,231.869995
2,2017-01-05,115.919998,116.860001,115.809998,116.610001,114.764473,22193600,Jan,Thursday,232.529999
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday,234.690003
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday,236.939995
...,...,...,...,...,...,...,...,...,...,...
164,2017-08-28,160.139999,162.000000,159.929993,161.470001,160.891617,25966000,Aug,Monday,321.610000
165,2017-08-29,160.100006,163.119995,160.000000,162.910004,162.326462,29516900,Aug,Tuesday,323.010010
166,2017-08-30,163.800003,163.889999,162.610001,163.350006,162.764893,27269600,Aug,Wednesday,327.150009
167,2017-08-31,163.639999,164.520004,163.479996,164.000000,163.412552,26785100,Aug,Thursday,327.639999
168,2017-09-01,164.800003,164.940002,163.630005,164.050003,163.462372,16591100,Sep,Friday,328.850006

In [19]:
#Create a new Column to store different sale price using eval()
stock_df.eval('Diff = Open-Close',inplace=True)

stock_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Total_sale,Diff
0,2017-01-03,115.800003,116.330002,114.760002,116.150002,114.311760,28781900,Jan,Tuesday,231.950005,-0.349999
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,114.183815,21118100,Jan,Wednesday,231.869995,-0.169999
2,2017-01-05,115.919998,116.860001,115.809998,116.610001,114.764473,22193600,Jan,Thursday,232.529999,-0.690003
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday,234.690003,-1.130005
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday,236.939995,-1.040001

<div class="alert alert-block alert-info">
<ul>
 <li>The inplace argument works as follows:</li>
    <ul>
     <li>inplace = <b>True</b> : perform the evaluation on the dataframe and updating/modifying the original dataframe</li>
     <li> inplace = <b>False</b>: will return a copy of dataframe when the modified done -(default)</li>
    </ul>
</ul>

## Delete columns/rows

In [20]:
# Delete column with the drop method
stock_df.drop(['Total_sale'], inplace = True, axis=1)
stock_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
0,2017-01-03,115.800003,116.330002,114.760002,116.150002,114.311760,28781900,Jan,Tuesday,-0.349999
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,114.183815,21118100,Jan,Wednesday,-0.169999
2,2017-01-05,115.919998,116.860001,115.809998,116.610001,114.764473,22193600,Jan,Thursday,-0.690003
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday,-1.130005
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday,-1.040001

In [21]:
#Delete rows with index 0 and 2
drop_rows = stock_df.drop([0,2], inplace = False, axis=0)
drop_rows.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,114.183815,21118100,Jan,Wednesday,-0.169999
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday,-1.130005
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday,-1.040001
5,2017-01-10,118.769997,119.379997,118.300003,119.110001,117.224907,24462100,Jan,Tuesday,-0.340004
6,2017-01-11,118.739998,119.930000,118.599998,119.750000,117.854782,27588600,Jan,Wednesday,-1.010002

In [22]:
stock_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
0,2017-01-03,115.800003,116.330002,114.760002,116.150002,114.311760,28781900,Jan,Tuesday,-0.349999
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,114.183815,21118100,Jan,Wednesday,-0.169999
2,2017-01-05,115.919998,116.860001,115.809998,116.610001,114.764473,22193600,Jan,Thursday,-0.690003
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday,-1.130005
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday,-1.040001

<div class="alert alert-block alert-info">
<ul>
 <li>The inplace argument works as follows:</li>
    <ul>
     <li>inplace = <b>True</b> : delete the given column(s) permanently from original dataframe</li>
     <li> inplace = <b>False</b>: will return a copy of dataframe where the removing is done - (default)</li>
    </ul>
 <li>The axis argument works as follows:</li>
    <ul>
     <li>axis = <b>1</b> : delete columns given</li>
     <li>axis = <b>0</b> : delete rows given</li>
    </ul>
</ul>
</div>

## Sorting
Let's see how we can sort a data frame.  The inplace argument has the same effect as the drop method.

In [23]:
#Sort the data frame according to the Volume Column from small to large
#By setting inplace= False will just return the sorted dataframe and not change df 
sorted_df = stock_df.sort_values(by = ['Volume'], inplace =False, ascending=True)

In [24]:
sorted_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
79,2017-04-27,143.919998,144.160004,143.309998,143.789993,142.127869,14246300,Apr,Thursday,0.130005
125,2017-07-03,144.880005,145.300003,143.100006,143.500000,142.426682,14258300,Jul,Monday,1.380005
72,2017-04-18,141.410004,142.039993,141.110001,141.199997,139.567795,14697500,Apr,Tuesday,0.210007
48,2017-03-14,139.300003,139.649994,138.839996,138.990005,137.383347,15309100,Mar,Tuesday,0.309998
141,2017-07-26,153.350006,153.929993,153.059998,153.460007,152.312180,15781000,Jul,Wednesday,-0.110001

In [25]:
stock_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
0,2017-01-03,115.800003,116.330002,114.760002,116.150002,114.311760,28781900,Jan,Tuesday,-0.349999
1,2017-01-04,115.849998,116.510002,115.750000,116.019997,114.183815,21118100,Jan,Wednesday,-0.169999
2,2017-01-05,115.919998,116.860001,115.809998,116.610001,114.764473,22193600,Jan,Thursday,-0.690003
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday,-1.130005
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday,-1.040001

In [26]:
#Sort the dataframe according to the Volume Column from large to small and replace the original df
stock_df.sort_values(by = ['Volume'], inplace =True, ascending=False)

In [27]:
stock_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
20,2017-02-01,127.029999,130.490005,127.010002,128.750000,126.712341,111985000,Feb,Wednesday,-1.720001
110,2017-06-12,145.740005,146.089996,142.509995,145.419998,144.332306,72307300,Jun,Monday,0.320007
146,2017-08-02,159.279999,159.750000,156.160004,157.139999,155.964661,69936800,Aug,Wednesday,2.140000
109,2017-06-09,155.190002,155.190002,146.020004,148.979996,147.865692,64882700,Jun,Friday,6.210006
93,2017-05-17,153.600006,154.570007,149.710007,150.250000,149.126190,50767700,May,Wednesday,3.350006

In [28]:
#Sort the dataframe according to the Weekday Column from first day of the weekday to last day of weekday
custom_dict = {'Monday':0, 'Tuesday':1, 'Wednesday':2, 'Thursday':3, 'Friday':4}
stock_df.sort_values(by = ['Weekday'], inplace =False, key=lambda x: x.map(custom_dict))

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
110,2017-06-12,145.740005,146.089996,142.509995,145.419998,144.332306,72307300,Jun,Monday,0.320007
86,2017-05-08,149.029999,153.699997,149.029999,153.009995,151.241272,48752400,May,Monday,-3.979996
4,2017-01-09,117.949997,119.430000,117.940002,118.989998,117.106812,33561900,Jan,Monday,-1.040001
81,2017-05-01,145.100006,147.199997,144.960007,146.580002,144.885605,33602900,May,Monday,-1.479996
115,2017-06-19,143.660004,146.740005,143.660004,146.339996,145.245438,32541400,Jun,Monday,-2.679992
...,...,...,...,...,...,...,...,...,...,...
133,2017-07-14,147.970001,149.330002,147.330002,149.039993,147.925232,20132100,Jul,Friday,-1.069992
27,2017-02-10,132.460007,132.940002,132.050003,132.119995,130.592758,20065500,Feb,Friday,0.340012
61,2017-03-31,143.720001,144.270004,143.009995,143.660004,141.999374,19661700,Mar,Friday,0.059997
66,2017-04-07,143.729996,144.179993,143.270004,143.339996,141.683060,16672200,Apr,Friday,0.390000
168,2017-09-01,164.800003,164.940002,163.630005,164.050003,163.462372,16591100,Sep,Friday,0.750000

We can also sort the values of the Series using the sort_values() function.<br>
Sorting the closing prices

In [29]:
#select only the "Close" price
close_price = stock_df['Close']
#Sort the closing prices in descending order.
sorted_close_price = close_price.sort_values(ascending=False)
sorted_close_price

168    164.050003
167    164.000000
166    163.350006
165    162.910004
155    161.600006
          ...
4      118.989998
3      117.910004
2      116.610001
0      116.150002
1      116.019997
Name: Close, Length: 169, dtype: float64

Now let's sort by multiple columns, specifying more than one column is essentially specifying a tie break

In [30]:
#Sort by Weekday and Close price

result_sorted = stock_df.sort_values(by = ['Weekday', 'Close'], inplace =False, ascending=[False,False])
result_sorted

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
166,2017-08-30,163.800003,163.889999,162.610001,163.350006,162.764893,27269600,Aug,Wednesday,0.449997
151,2017-08-09,159.259995,161.270004,159.110001,161.059998,159.855331,26131500,Aug,Wednesday,-1.800003
156,2017-08-16,161.940002,162.509995,160.149994,160.949997,160.373474,27671600,Aug,Wednesday,0.990005
161,2017-08-23,159.070007,160.470001,158.880005,159.979996,159.406952,19399100,Aug,Wednesday,-0.909989
146,2017-08-02,159.279999,159.750000,156.160004,157.139999,155.964661,69936800,Aug,Wednesday,2.140000
...,...,...,...,...,...,...,...,...,...,...
22,2017-02-03,128.309998,129.190002,128.160004,129.080002,127.037125,24507300,Feb,Friday,-0.770004
17,2017-01-27,122.139999,122.349998,121.599998,121.949997,120.019958,20562900,Jan,Friday,0.190002
12,2017-01-20,120.449997,120.449997,119.730003,120.000000,118.100822,32597900,Jan,Friday,0.449997
8,2017-01-13,119.110001,119.620003,118.809998,119.040001,117.156021,26111900,Jan,Friday,0.070000
3,2017-01-06,116.779999,118.160004,116.470001,117.910004,116.043915,31751900,Jan,Friday,-1.130005

In [31]:
#Sort by Volume and Close price

result_sorted_2 = stock_df.sort_values(by = ['Volume', 'Close'], inplace =False, ascending=[False,False])
result_sorted_2

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
20,2017-02-01,127.029999,130.490005,127.010002,128.750000,126.712341,111985000,Feb,Wednesday,-1.720001
110,2017-06-12,145.740005,146.089996,142.509995,145.419998,144.332306,72307300,Jun,Monday,0.320007
146,2017-08-02,159.279999,159.750000,156.160004,157.139999,155.964661,69936800,Aug,Wednesday,2.140000
109,2017-06-09,155.190002,155.190002,146.020004,148.979996,147.865692,64882700,Jun,Friday,6.210006
93,2017-05-17,153.600006,154.570007,149.710007,150.250000,149.126190,50767700,May,Wednesday,3.350006
...,...,...,...,...,...,...,...,...,...,...
141,2017-07-26,153.350006,153.929993,153.059998,153.460007,152.312180,15781000,Jul,Wednesday,-0.110001
48,2017-03-14,139.300003,139.649994,138.839996,138.990005,137.383347,15309100,Mar,Tuesday,0.309998
72,2017-04-18,141.410004,142.039993,141.110001,141.199997,139.567795,14697500,Apr,Tuesday,0.210007
125,2017-07-03,144.880005,145.300003,143.100006,143.500000,142.426682,14258300,Jul,Monday,1.380005
79,2017-04-27,143.919998,144.160004,143.309998,143.789993,142.127869,14246300,Apr,Thursday,0.130005

## groupby
<font szie=3>Using <b>groupby</b> method we can:</font>
- <font szie=3>Split the data into groups based on some criteria</font>
- <font szie=3>Calculate statistics (or apply a function) to each group</font>

In [32]:
# Group apple stock price by month
stock_price_monthly=stock_df.groupby('Month')

In [33]:
#Use a for loop to iterate through the key, item pairs in the DataFrameGroupBy object
for group, item_in_group in stock_price_monthly:
    print(f"Group: {group}")
    print(item_in_group)

Group: Apr
         Date        Open        High         Low       Close   Adj Close  \
68 2017-04-11  142.940002  143.350006  140.059998  141.630005  139.992844
64 2017-04-05  144.220001  145.460007  143.809998  144.020004  142.355209
74 2017-04-20  141.220001  142.919998  141.160004  142.440002  140.793457
65 2017-04-06  144.289993  144.520004  143.449997  143.660004  141.999374
80 2017-04-28  144.089996  144.300003  143.270004  143.649994  141.989456
69 2017-04-12  141.600006  142.149994  141.009995  141.800003  140.160873
78 2017-04-26  144.470001  144.600006  143.380005  143.679993  142.019119
62 2017-04-03  143.710007  144.119995  143.050003  143.699997  142.038910
63 2017-04-04  143.250000  144.889999  143.169998  144.770004  143.096542
67 2017-04-10  143.600006  143.880005  142.899994  143.169998  141.515030
77 2017-04-25  143.910004  144.899994  143.869995  144.529999  142.859299
70 2017-04-13  141.910004  142.380005  141.050003  141.050003  139.419540
73 2017-04-19  141.880005  142.000000  140.449997  140.679993  139.053818
75 2017-04-21  142.440002  142.679993  141.850006  142.270004  140.625443
76 2017-04-24  143.500000  143.949997  143.179993  143.639999  141.979584
66 2017-04-07  143.729996  144.179993  143.270004  143.339996  141.683060
71 2017-04-17  141.479996  141.880005  140.869995  141.830002  140.190521
72 2017-04-18  141.410004  142.039993  141.110001  141.199997  139.567795
79 2017-04-27  143.919998  144.160004  143.309998  143.789993  142.127869

      Volume Month    Weekday      Diff
68  30379400   Apr    Tuesday  1.309997
64  27717900   Apr  Wednesday  0.199997
74  23319600   Apr   Thursday -1.220001
65  21149000   Apr   Thursday  0.629989
80  20860400   Apr     Friday  0.440002
69  20350000   Apr  Wednesday -0.199997
78  20041200   Apr  Wednesday  0.790008
62  19985700   Apr     Monday  0.010010
63  19891400   Apr    Tuesday -1.520004
67  18933400   Apr     Monday  0.430008
77  18871500   Apr    Tuesday -0.619995
70  17822900   Apr   Thursday  0.860001
73  17328400   Apr  Wednesday  1.200012
75  17320900   Apr     Friday  0.169998
76  17134300   Apr     Monday -0.139999
66  16672200   Apr     Friday  0.390000
71  16582100   Apr     Monday -0.350006
72  14697500   Apr    Tuesday  0.210007
79  14246300   Apr   Thursday  0.130005
Group: Aug
          Date        Open        High         Low       Close   Adj Close  \
146 2017-08-02  159.279999  159.750000  156.160004  157.139999  155.964661
152 2017-08-10  159.899994  160.000000  154.630005  155.320007  154.763657
150 2017-08-08  158.600006  161.830002  158.270004  160.080002  158.882660
145 2017-08-01  149.100006  150.220001  148.410004  150.050003  148.927689
165 2017-08-29  160.100006  163.119995  160.000000  162.910004  162.326462
155 2017-08-15  160.660004  162.199997  160.139999  161.600006  161.021149
157 2017-08-17  160.520004  160.710007  157.839996  157.860001  157.294540
156 2017-08-16  161.940002  162.509995  160.149994  160.949997  160.373474
158 2017-08-18  157.860001  159.500000  156.720001  157.500000  156.935837
166 2017-08-30  163.800003  163.889999  162.610001  163.350006  162.764893
147 2017-08-03  157.050003  157.210007  155.020004  155.570007  154.406403
167 2017-08-31  163.639999  164.520004  163.479996  164.000000  163.412552
159 2017-08-21  157.500000  157.889999  155.110001  157.210007  156.646881
153 2017-08-11  156.600006  158.570007  156.070007  157.479996  156.915909
151 2017-08-09  159.259995  161.270004  159.110001  161.059998  159.855331
164 2017-08-28  160.139999  162.000000  159.929993  161.470001  160.891617
163 2017-08-25  159.649994  160.559998  159.270004  159.860001  159.287384
154 2017-08-14  159.320007  160.210007  158.750000  159.850006  159.277420
149 2017-08-07  157.059998  158.919998  156.669998  158.809998  157.622162
160 2017-08-22  158.229996  160.000000  158.020004  159.779999  159.207672
148 2017-08-04  156.070007  157.399994  155.690002  156.389999  155.220261
162 2017-08-24  160.429993  160.740005  158.550003  159.270004  158.699493
161 2017-08-23  159.070007  160.470001  158.880005  159.979996  159.406952

       Volume Month    Weekday      Diff
146  69936800   Aug  Wednesday  2.140000
152  40804300   Aug   Thursday  4.579987
150  36205900   Aug    Tuesday -1.479996
145  35368600   Aug    Tuesday -0.949997
165  29516900   Aug    Tuesday -2.809998
155  29465500   Aug    Tuesday -0.940002
157  27940600   Aug   Thursday  2.660003
156  27671600   Aug  Wednesday  0.990005
158  27428100   Aug     Friday  0.360001
166  27269600   Aug  Wednesday  0.449997
147  27097300   Aug   Thursday  1.479996
167  26785100   Aug   Thursday -0.360001
159  26368500   Aug     Monday  0.289993
153  26257100   Aug     Friday -0.879990
151  26131500   Aug  Wednesday -1.800003
164  25966000   Aug     Monday -1.330002
163  25480100   Aug     Friday -0.210007
154  22122700   Aug     Monday -0.529999
149  21870300   Aug     Monday -1.750000
160  21604600   Aug    Tuesday -1.550003
148  20559900   Aug     Friday -0.319992
162  19818900   Aug   Thursday  1.159989
161  19399100   Aug  Wednesday -0.909989
Group: Feb
         Date        Open        High         Low       Close   Adj Close  \
20 2017-02-01  127.029999  130.490005  127.010002  128.750000  126.712341
24 2017-02-07  130.539993  132.089996  130.449997  131.529999  129.448349
30 2017-02-15  135.520004  136.270004  134.619995  135.509995  133.943573
21 2017-02-02  127.980003  129.389999  127.779999  128.529999  126.495819
29 2017-02-14  133.470001  135.089996  133.250000  135.020004  133.459244
26 2017-02-09  131.649994  132.449997  131.119995  132.419998  130.889282
23 2017-02-06  129.130005  130.500000  128.899994  130.289993  128.227966
22 2017-02-03  128.309998  129.190002  128.160004  129.080002  127.037125
33 2017-02-21  136.229996  136.750000  135.979996  136.699997  135.119827
38 2017-02-28  137.080002  137.440002  136.699997  136.990005  135.406479
28 2017-02-13  133.080002  133.820007  132.750000  133.289993  131.749222
25 2017-02-08  131.350006  132.220001  131.220001  132.039993  129.950287
31 2017-02-16  135.669998  135.899994  134.839996  135.350006  133.785416
32 2017-02-17  135.100006  135.830002  135.100006  135.720001  134.151154
36 2017-02-24  135.910004  136.660004  135.279999  136.660004  135.080292
34 2017-02-22  136.429993  137.119995  136.110001  137.110001  135.525070
35 2017-02-23  137.380005  137.479996  136.300003  136.529999  134.951782
37 2017-02-27  137.139999  137.440002  136.279999  136.929993  135.347153
27 2017-02-10  132.460007  132.940002  132.050003  132.119995  130.592758

       Volume Month    Weekday      Diff
20  111985000   Feb  Wednesday -1.720001
24   38183800   Feb    Tuesday -0.990006
30   35623100   Feb  Wednesday  0.010009
21   33710400   Feb   Thursday -0.549996
29   33226200   Feb    Tuesday -1.550003
26   28349900   Feb   Thursday -0.770004
23   26845900   Feb     Monday -1.159988
22   24507300   Feb     Friday -0.770004
33   24507200   Feb    Tuesday -0.470001
38   23482900   Feb    Tuesday  0.089997
28   23035400   Feb     Monday -0.209991
25   23004100   Feb  Wednesday -0.689987
31   22584600   Feb   Thursday  0.319992
32   22198200   Feb     Friday -0.619995
36   21776600   Feb     Friday -0.750000
34   20836900   Feb  Wednesday -0.680008
35   20788200   Feb   Thursday  0.850006
37   20257400   Feb     Monday  0.210006
27   20065500   Feb     Friday  0.340012
Group: Jan
         Date        Open        High         Low       Close   Adj Close  \
19 2017-01-31  121.150002  121.389999  120.620003  121.349998  119.429459
9  2017-01-17  118.339996  120.239998  118.220001  120.000000  118.100822
4  2017-01-09  117.949997  119.430000  117.940002  118.989998  117.106812
12 2017-01-20  120.449997  120.449997  119.730003  120.000000  118.100822
15 2017-01-25  120.419998  122.099998  120.279999  121.879997  119.951073
3  2017-01-06  116.779999  118.160004  116.470001  117.910004  116.043915
18 2017-01-30  120.930000  121.629997  120.660004  121.629997  119.705017
0  2017-01-03  115.800003  116.330002  114.760002  116.150002  114.311760
6  2017-01-11  118.739998  119.930000  118.599998  119.750000  117.854782
7  2017-01-12  118.900002  119.300003  118.209999  119.250000  117.362694
16 2017-01-26  121.669998  122.440002  121.599998  121.940002  120.010132
8  2017-01-13  119.110001  119.620003  118.809998  119.040001  117.156021
11 2017-01-19  119.400002  120.089996  119.370003  119.779999  117.884300
5  2017-01-10  118.769997  119.379997  118.300003  119.110001  117.224907
10 2017-01-18  120.000000  120.500000  119.709999  119.989998  118.090981
14 2017-01-24  119.550003  120.099998  119.500000  119.970001  118.071304
2  2017-01-05  115.919998  116.860001  115.809998  116.610001  114.764473
13 2017-01-23  120.000000  120.809998  119.769997  120.080002  118.179558
1  2017-01-04  115.849998  116.510002  115.750000  116.019997  114.183815
17 2017-01-27  122.139999  122.349998  121.599998  121.949997  120.019958

      Volume Month    Weekday      Diff
19  49201000   Jan    Tuesday -0.199996
9   34439800   Jan    Tuesday -1.660004
4   33561900   Jan     Monday -1.040001
12  32597900   Jan     Friday  0.449997
15  32377600   Jan  Wednesday -1.459999
3   31751900   Jan     Friday -1.130005
18  30377500   Jan     Monday -0.699997
0   28781900   Jan    Tuesday -0.349999
6   27588600   Jan  Wednesday -1.010002
7   27086200   Jan   Thursday -0.349998
16  26337600   Jan   Thursday -0.270004
8   26111900   Jan     Friday  0.070000
11  25597300   Jan   Thursday -0.379997
5   24462100   Jan    Tuesday -0.340004
10  23713000   Jan  Wednesday  0.010002
14  23211000   Jan    Tuesday -0.419998
2   22193600   Jan   Thursday -0.690003
13  22050200   Jan     Monday -0.080002
1   21118100   Jan  Wednesday -0.169999
17  20562900   Jan     Friday  0.190002
Group: Jul
          Date        Open        High         Low       Close   Adj Close  \
142 2017-07-27  153.750000  153.990005  147.300003  150.559998  149.433868
138 2017-07-21  149.990005  150.440002  148.880005  150.270004  149.146042
132 2017-07-13  145.500000  148.490005  145.440002  147.770004  146.664749
131 2017-07-12  145.869995  146.179993  144.820007  145.740005  144.649918
127 2017-07-06  143.020004  143.500000  142.410004  142.729996  141.662430
134 2017-07-17  148.820007  150.899994  148.570007  149.559998  148.441345
126 2017-07-05  143.690002  144.789993  142.720001  144.089996  143.012253
139 2017-07-24  150.580002  152.440002  149.899994  152.089996  150.952423
129 2017-07-10  144.110001  145.949997  143.369995  145.059998  143.975006
136 2017-07-19  150.479996  151.419998  149.949997  151.020004  149.890442
133 2017-07-14  147.970001  149.330002  147.330002  149.039993  147.925232
144 2017-07-31  149.899994  150.330002  148.130005  148.729996  147.617554
130 2017-07-11  144.729996  145.850006  144.380005  145.529999  144.441483
128 2017-07-07  142.899994  144.750000  142.899994  144.179993  143.101578
140 2017-07-25  151.800003  153.839996  151.800003  152.740005  151.597580
135 2017-07-18  149.199997  150.130005  148.669998  150.080002  148.957474
137 2017-07-20  151.500000  151.740005  150.190002  150.339996  149.215515
143 2017-07-28  149.889999  150.229996  149.190002  149.500000  148.381790
141 2017-07-26  153.350006  153.929993  153.059998  153.460007  152.312180
125 2017-07-03  144.880005  145.300003  143.100006  143.500000  142.426682

       Volume Month    Weekday      Diff
142  32476300   Jul   Thursday  3.190002
138  26252600   Jul     Friday -0.279999
132  25199400   Jul   Thursday -2.270004
131  24884500   Jul  Wednesday  0.129990
127  24128800   Jul   Thursday  0.290008
134  23793500   Jul     Monday -0.739991
126  21569600   Jul  Wednesday -0.399994
139  21493200   Jul     Monday -1.509994
129  21090600   Jul     Monday -0.949997
136  20923000   Jul  Wednesday -0.540008
133  20132100   Jul     Friday -1.069992
144  19845900   Jul     Monday  1.169998
130  19781800   Jul    Tuesday -0.800003
128  19201700   Jul     Friday -1.279999
140  18853900   Jul    Tuesday -0.940002
135  17868800   Jul    Tuesday -0.880005
137  17243700   Jul   Thursday  1.160004
143  17213700   Jul     Friday  0.389999
141  15781000   Jul  Wednesday -0.110001
125  14258300   Jul     Monday  1.380005
Group: Jun
          Date        Open        High         Low       Close   Adj Close  \
110 2017-06-12  145.740005  146.089996  142.509995  145.419998  144.332306
109 2017-06-09  155.190002  155.190002  146.020004  148.979996  147.865692
114 2017-06-16  143.779999  144.500000  142.199997  142.270004  141.205887
119 2017-06-23  145.130005  147.160004  145.110001  146.279999  145.185883
111 2017-06-13  147.160004  147.449997  145.149994  146.589996  145.493561
115 2017-06-19  143.660004  146.740005  143.660004  146.339996  145.245438
113 2017-06-15  143.320007  144.479996  142.210007  144.289993  143.210754
112 2017-06-14  147.500000  147.500000  143.839996  145.160004  144.074265
123 2017-06-29  144.710007  145.130005  142.279999  143.679993  142.605316
104 2017-06-02  153.580002  155.449997  152.889999  155.449997  154.287292
106 2017-06-06  153.899994  155.809998  153.779999  154.449997  153.294785
120 2017-06-26  147.169998  148.279999  145.380005  145.820007  144.729340
105 2017-06-05  154.339996  154.449997  153.460007  153.929993  152.778656
116 2017-06-20  146.869995  146.869995  144.940002  145.009995  143.925369
121 2017-06-27  145.009995  146.160004  143.619995  143.729996  142.654953
124 2017-06-30  144.449997  144.960007  143.779999  144.020004  142.942795
122 2017-06-28  144.490005  146.110001  143.160004  145.830002  144.739243
117 2017-06-21  145.520004  146.070007  144.610001  145.869995  144.778946
108 2017-06-08  155.250000  155.539993  154.399994  154.990005  153.830734
107 2017-06-07  155.020004  155.979996  154.479996  155.369995  154.207901
118 2017-06-22  145.770004  146.699997  145.119995  145.630005  144.540756
103 2017-06-01  153.169998  153.330002  152.220001  153.179993  152.034271

       Volume Month    Weekday      Diff
110  72307300   Jun     Monday  0.320007
109  64882700   Jun     Friday  6.210006
114  50361100   Jun     Friday  1.509995
119  35439400   Jun     Friday -1.149994
111  34165400   Jun    Tuesday  0.570008
115  32541400   Jun     Monday -2.679992
113  32165400   Jun   Thursday -0.969986
112  31531200   Jun  Wednesday  2.339996
123  31499400   Jun   Thursday  1.030014
104  27770700   Jun     Friday -1.869995
106  26624900   Jun    Tuesday -0.550003
120  25692400   Jun     Monday  1.349991
105  25331700   Jun     Monday  0.410003
116  24900100   Jun    Tuesday  1.860000
121  24761900   Jun    Tuesday  1.279999
124  23024100   Jun     Friday  0.429993
122  22082400   Jun  Wednesday -1.339997
117  21265800   Jun  Wednesday -0.349991
108  21250800   Jun   Thursday  0.259995
107  21069600   Jun  Wednesday -0.349991
118  19106300   Jun   Thursday  0.139999
103  16404100   Jun   Thursday -0.009995
Group: Mar
         Date        Open        High         Low       Close   Adj Close  \
51 2017-03-17  141.000000  141.000000  139.889999  139.990005  138.371780
53 2017-03-21  142.110001  142.800003  139.729996  139.839996  138.223511
39 2017-03-01  137.889999  140.149994  137.600006  139.789993  138.174088
58 2017-03-28  140.910004  144.039993  140.619995  143.800003  142.137741
59 2017-03-29  143.679993  144.490005  143.190002  144.119995  142.454041
40 2017-03-02  140.000000  140.279999  138.759995  138.960007  137.353699
54 2017-03-22  139.850006  141.600006  139.759995  141.419998  139.785248
49 2017-03-15  139.410004  140.750000  139.029999  140.460007  138.836365
57 2017-03-27  139.389999  141.220001  138.619995  140.880005  139.251511
56 2017-03-24  141.500000  141.740005  140.350006  140.639999  139.014267
45 2017-03-09  138.740005  138.789993  137.050003  138.679993  137.076920
42 2017-03-06  139.369995  139.770004  138.600006  139.339996  137.729309
52 2017-03-20  140.399994  141.500000  140.229996  141.460007  139.824799
60 2017-03-30  144.190002  144.500000  143.500000  143.929993  142.266235
41 2017-03-03  138.779999  139.830002  138.589996  139.779999  138.164200
55 2017-03-23  141.259995  141.580002  140.610001  140.919998  139.291031
61 2017-03-31  143.720001  144.270004  143.009995  143.660004  141.999374
46 2017-03-10  139.250000  139.360001  138.639999  139.139999  137.531601
50 2017-03-16  140.720001  141.020004  140.259995  140.690002  139.063690
44 2017-03-08  138.949997  139.800003  138.820007  139.000000  137.393234
43 2017-03-07  139.059998  139.979996  138.789993  139.520004  137.907227
47 2017-03-13  138.850006  139.429993  138.820007  139.199997  137.590912
48 2017-03-14  139.300003  139.649994  138.839996  138.990005  137.383347

      Volume Month    Weekday      Diff
51  43885000   Mar     Friday  1.009995
53  39529900   Mar    Tuesday  2.270005
39  36414600   Mar  Wednesday -1.899994
58  33374800   Mar    Tuesday -2.889999
59  29190000   Mar  Wednesday -0.440002
40  26211000   Mar   Thursday  1.039993
54  25860200   Mar  Wednesday -1.569992
49  25691800   Mar  Wednesday -1.050003
57  23575100   Mar     Monday -1.490006
56  22395600   Mar     Friday  0.860001
45  22155900   Mar   Thursday  0.060012
42  21750000   Mar     Monday  0.029999
52  21542000   Mar     Monday -1.060013
60  21207300   Mar   Thursday  0.260009
41  21108100   Mar     Friday -1.000000
55  20346300   Mar   Thursday  0.339997
61  19661700   Mar     Friday  0.059997
46  19612800   Mar     Friday  0.110001
50  19232000   Mar   Thursday  0.029999
44  18707200   Mar  Wednesday -0.050003
43  17446300   Mar    Tuesday -0.460006
47  17421700   Mar     Monday -0.349991
48  15309100   Mar    Tuesday  0.309998
Group: May
          Date        Open        High         Low       Close   Adj Close  \
93  2017-05-17  153.600006  154.570007  149.710007  150.250000  149.126190
86  2017-05-08  149.029999  153.699997  149.029999  153.009995  151.241272
83  2017-05-03  145.589996  147.490005  144.270004  147.059998  145.360062
82  2017-05-02  147.539993  148.089996  146.839996  147.509995  145.804855
87  2017-05-09  153.869995  154.880005  153.449997  153.990005  152.209961
81  2017-05-01  145.100006  147.199997  144.960007  146.580002  144.885605
94  2017-05-18  151.270004  153.339996  151.130005  152.539993  151.399048
90  2017-05-12  154.699997  156.419998  154.669998  156.100006  154.932449
85  2017-05-05  146.759995  148.979996  146.759995  148.960007  147.238113
89  2017-05-11  152.449997  154.070007  152.309998  153.949997  152.798523
95  2017-05-19  153.380005  153.979996  152.630005  153.059998  151.915176
91  2017-05-15  156.009995  156.649994  155.050003  155.699997  154.535416
88  2017-05-10  153.630005  153.940002  152.110001  153.259995  151.488388
102 2017-05-31  153.970001  154.169998  152.380005  152.759995  151.617416
84  2017-05-04  146.520004  147.139999  145.809998  146.529999  144.836182
96  2017-05-22  154.000000  154.580002  152.910004  153.990005  152.838211
100 2017-05-26  154.000000  154.240005  153.309998  153.610001  152.461060
101 2017-05-30  153.419998  154.429993  153.330002  153.669998  152.520599
92  2017-05-16  155.940002  156.059998  154.720001  155.470001  154.307144
97  2017-05-23  154.899994  154.899994  153.309998  153.800003  152.649643
99  2017-05-25  153.729996  154.350006  153.029999  153.869995  152.719101
98  2017-05-24  153.839996  154.169998  152.669998  153.339996  152.193069

       Volume Month    Weekday      Diff
93   50767700   May  Wednesday  3.350006
86   48752400   May     Monday -3.979996
83   45697000   May  Wednesday -1.470002
82   45352200   May    Tuesday  0.029998
87   39130400   May    Tuesday -0.120010
81   33602900   May     Monday -1.479996
94   33568200   May   Thursday -1.269989
90   32527000   May     Friday -1.400009
85   27327700   May     Friday -2.200012
89   27255100   May   Thursday -1.500000
95   26960800   May     Friday  0.320007
91   26009700   May     Monday  0.309998

We can determine the number of rows in each group using the size method, which tells us the `size` of each group.

In [34]:
# get the total number of row count for each group
stock_df.groupby('Month').size()

Month
Apr    19
Aug    23
Feb    19
Jan    20
Jul    20
Jun    22
Mar    23
May    22
Sep     1
dtype: int64

In [35]:
# Access individual group using DataFrameGroupBy.get_group(key)
stock_price_monthly.get_group('Jun')

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Weekday,Diff
110,2017-06-12,145.740005,146.089996,142.509995,145.419998,144.332306,72307300,Jun,Monday,0.320007
109,2017-06-09,155.190002,155.190002,146.020004,148.979996,147.865692,64882700,Jun,Friday,6.210006
114,2017-06-16,143.779999,144.500000,142.199997,142.270004,141.205887,50361100,Jun,Friday,1.509995
119,2017-06-23,145.130005,147.160004,145.110001,146.279999,145.185883,35439400,Jun,Friday,-1.149994
111,2017-06-13,147.160004,147.449997,145.149994,146.589996,145.493561,34165400,Jun,Tuesday,0.570008
115,2017-06-19,143.660004,146.740005,143.660004,146.339996,145.245438,32541400,Jun,Monday,-2.679992
113,2017-06-15,143.320007,144.479996,142.210007,144.289993,143.210754,32165400,Jun,Thursday,-0.969986
112,2017-06-14,147.500000,147.500000,143.839996,145.160004,144.074265,31531200,Jun,Wednesday,2.339996
123,2017-06-29,144.710007,145.130005,142.279999,143.679993,142.605316,31499400,Jun,Thursday,1.030014
104,2017-06-02,153.580002,155.449997,152.889999,155.449997,154.287292,27770700,Jun,Friday,-1.869995
106,2017-06-06,153.899994,155.809998,153.779999,154.449997,153.294785,26624900,Jun,Tuesday,-0.550003
120,2017-06-26,147.169998,148.279999,145.380005,145.820007,144.729340,25692400,Jun,Monday,1.349991
105,2017-06-05,154.339996,154.449997,153.460007,153.929993,152.778656,25331700,Jun,Monday,0.410003
116,2017-06-20,146.869995,146.869995,144.940002,145.009995,143.925369,24900100,Jun,Tuesday,1.860000
121,2017-06-27,145.009995,146.160004,143.619995,143.729996,142.654953,24761900,Jun,Tuesday,1.279999
124,2017-06-30,144.449997,144.960007,143.779999,144.020004,142.942795,23024100,Jun,Friday,0.429993
122,2017-06-28,144.490005,146.110001,143.160004,145.830002,144.739243,22082400,Jun,Wednesday,-1.339997
117,2017-06-21,145.520004,146.070007,144.610001,145.869995,144.778946,21265800,Jun,Wednesday,-0.349991
108,2017-06-08,155.250000,155.539993,154.399994,154.990005,153.830734,21250800,Jun,Thursday,0.259995
107,2017-06-07,155.020004,155.979996,154.479996,155.369995,154.207901,21069600,Jun,Wednesday,-0.349991
118,2017-06-22,145.770004,146.699997,145.119995,145.630005,144.540756,19106300,Jun,Thursday,0.139999
103,2017-06-01,153.169998,153.330002,152.220001,153.179993,152.034271,16404100,Jun,Thursday,-0.009995

In [36]:
#Calculate mean value for open price in each month
stock_df.groupby('Month').Open.mean()

Month
Apr    143.030001
Aug    158.946958
Feb    133.234738
Jan    119.093499
Jul    148.096500
Jun    148.215001
Mar    140.362174
May    151.965908
Sep    164.800003
Name: Open, dtype: float64

We can also group datetime values in a DataFrame to calculate statistics like averages or counts over time periods such as days, weeks, or months.

In [37]:
# Group by month and calculate average closing price
stock_df.groupby(stock_df.Date.dt.month)['Close'].mean()

Date
1    119.570000
2    133.714209
3    140.617826
4    142.886842
5    152.227726
6    147.831362
7    148.299499
8    159.021306
9    164.050003
Name: Close, dtype: float64

Once groupby object is create we can calculate various statistics for each group

In [38]:
#Find the average open price and the average volume in each month. 
stock_df.groupby('Month')[['Open', 'Volume']].mean()

             Open        Volume
Month
Apr    143.030001  1.964758e+07
Aug    158.946958  2.874213e+07
Feb    133.234738  3.026151e+07
Jan    119.093499  2.815610e+07
Jul    148.096500  2.109962e+07
Jun    148.215001  3.109900e+07
Mar    140.362174  2.441863e+07
May    151.965908  2.971615e+07
Sep    164.800003  1.659110e+07

<font size=3>You can specify a list of column names for the argument in the group by to accomplish this.</font>

In [ ]:
#Groupby multiple columns: open price for each month and each day of the week.
stock_df.groupby(['Month', 'Weekday']).Open.mean().head(10)

Month  Weekday
Apr    Friday       143.419998
       Monday       143.072502
       Thursday     142.834999
       Tuesday      142.877502
       Wednesday    143.042503
Aug    Friday       157.545002
       Monday       158.505001
       Thursday     160.307999
       Tuesday      157.338004
       Wednesday    160.670001
Name: Open, dtype: float64

<font size=3>Now, we have a group for every month + weekday combination. The above is a series with multi-level, we can slice these series by resetting the index, which will move the multilevel index to columns in your dataframe.</font>

In [40]:
stock_df.groupby(['Month', 'Weekday']).Open.mean().reset_index().head(15)

   Month    Weekday        Open
0    Apr     Friday  143.419998
1    Apr     Monday  143.072502
2    Apr   Thursday  142.834999
3    Apr    Tuesday  142.877502
4    Apr  Wednesday  143.042503
5    Aug     Friday  157.545002
6    Aug     Monday  158.505001
7    Aug   Thursday  160.307999
8    Aug    Tuesday  157.338004
9    Aug  Wednesday  160.670001
10   Feb     Friday  132.945004
11   Feb     Monday  133.116669
12   Feb   Thursday  133.170000
13   Feb    Tuesday  134.329998
14   Feb  Wednesday  132.582501

## Filtering Rows
<font size=3>In this section, we will see how to select only the rows of a dataframe that satisfy certain condition(s).</font>
- <font size=3>Filtering is performed using so-called Boolean arrays</font>
- <font size=3>To subset the data we can apply Boolean indexing. This indexing is commonly known as a filter</font>
- <font size=3>Any Boolean operator can be used to subset the data:</font>
    - <font size=3> <b> $>$ </b> greater</font>
    - <font size=3><b> $<$ </b> less</font>
    - <font size=3><b> $==$ </b> equal</font>
    - <font size=3><b> $>=$ </b> greater or equal</font>
    - <font size=3><b> $<=$ </b> less or equal</font>
    - <font size=3><b> $!=$ </b> not equal</font>

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models).
- mpg: Miles/(US) gallon
- cyl: Number of cylinders
- disp: Displacement (cu.in.)
- hp: Gross horsepower
- drat: Rear axle ratio
- wt: Weight (1000 lbs)
- qsec: 1/4 mile time
- vs: V/S
- am: Transmission (0 = automatic, 1 = manual)
- gear: Number of forward gears
- carb: Number of carburetors

In [41]:
import pandas as pd

file_path = "./Data/mtcars.csv"
try:
    #Read in the data frame
    df_mtcars=pd.read_csv(file_path, encoding='utf-8')
except FileNotFoundError as e1:
    print(f"File not found - {e1}")
except Exception as e2:
    print(f"Exception - {e2}")

df_mtcars.head()

,car_name,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [42]:
#Picking out rows that only correspond to cars with >=150 hp + all columns
fast_cars_150hp = df_mtcars.loc[df_mtcars.hp >= 150, :]

fast_cars_150hp

,car_name,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [43]:
#Select our cars with am = 1 and only look at columns mpg, hp, am
df_mtcars.loc[df_mtcars.am ==1, ['mpg', 'hp', 'am']]

     mpg   hp  am
0   21.0  110   1
1   21.0  110   1
2   22.8   93   1
17  32.4   66   1
18  30.4   52   1
19  33.9   65   1
25  27.3   66   1
26  26.0   91   1
27  30.4  113   1
28  15.8  264   1
29  19.7  175   1
30  15.0  335   1
31  21.4  109   1

<font size=3>We can filter rows based on conditions from a Series as well.</font>

In [44]:
#Select our cars with am = 1 and only look at columns mpg
manual_car = df_mtcars.loc[df_mtcars.am ==1, 'mpg']
manual_car

0     21.0
1     21.0
2     22.8
17    32.4
18    30.4
19    33.9
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

<font size=3>Filter on multiple condition. For an "and" clause use & and for an "or" clause use |. Make sure to put each clause in parentheses. </font>

In [45]:
#Select all cars with 6 cylinders and 4 gears + all columns
df_mtcars.loc[(df_mtcars.cyl == 6) & (df_mtcars.gear == 4), :]

,car_name,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4

In [46]:
#Select all cars with either 4 or 6 cylinders and show only mpg, hp, and gear
df_mtcars.loc[(df_mtcars.cyl == 4) | (df_mtcars.cyl == 6), ['mpg', 'hp', 'gear']]

     mpg   hp  gear
0   21.0  110     4
1   21.0  110     4
2   22.8   93     4
3   21.4  110     3
5   18.1  105     3
7   24.4   62     4
8   22.8   95     4
9   19.2  123     4
10  17.8  123     4
17  32.4   66     4
18  30.4   52     4
19  33.9   65     4
20  21.5   97     3
25  27.3   66     4
26  26.0   91     5
27  30.4  113     5
29  19.7  175     5
31  21.4  109     4

<font size=3>We can also use a variable in the conditions</font>

In [47]:
transmission = int(input("Enter transimission type [0 = auto/ 1= manual]: "))
horsepower = int(input("Enter horse power: "))

#Select all cars with criteria received from a user
df_mtcars.loc[(df_mtcars.am == transmission) & (df_mtcars.hp == horsepower), :]

Empty DataFrame
Columns: [car_name, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb]
Index: []

***

# Summary

- <font size=3>We can perfrom basic calculation on a dataframe: mean(), max(), min(), describe(), std(), sum()</font>
- <font size=3>We can create new columns and delete columns in a dataframe<</font>
- <font size=3>Useful a dataframe manipulations:groupby(), sort_values(), filter()</font>

***