# Exercise: Chinese Supermarket

Analyse the data in the "Purchase_Data.csv" file, which records purchases at a Chinese supermarket for various products, to address the specified tasks and obtain answers to the following questions.

## Import pandas and read this csv into a dataframe called purchase_df

In [1]:
#Write your code here

import pandas as pd

# the Jupyter Notebook is in the same location as your dataset
file_name = "Purchase_data.csv"
try: 
    purchase_df = pd.read_csv(file_name, encoding='utf-8')
except FileNotFoundError as e1:
    print(f"File not found - {e1}")
except Exception as e2:
    print(f"Exception - {e2}")

## Display 5 first record of dataframe

In [3]:
#Write your code here
purchase_df.head(5)

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,10107,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,10121,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,10134,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,10145,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,10159,7/15/15 12:16,G816,7090363,70401,1.0,6.0

## Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [4]:
#Write your code here

avg_price = purchase_df.price.mean()
max_price =purchase_df.price.max()

print(f"Average price: £{avg_price:.2f}")
print(f"Maximum price: £{max_price:.2f}")

Average price: £3.13
Maximum price: £6.00

## Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [5]:
#Write your code here
avgs = purchase_df[["price", "num_item"]].mean()
avg_price = avgs.loc["price"]
avg_num_items = avgs.loc["num_item"]

print(f"Average price: {avg_price:.2f}")
print(f"Avergae number of items: {avg_num_items:.2f}")

Average price: 3.13
Avergae number of items: 1.25

## Convert 'invoice_time' column to be datetime format and update the original DataFrame with this change.

In [6]:
purchase_df['invoice_time'] = pd.to_datetime(purchase_df['invoice_time'],format='mixed',dayfirst=True)
purchase_df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,10107,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0
1,10121,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0
2,10134,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0
3,10145,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0
4,10159,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0

## Group the purchase transactions by store_id and save the result in a new variable called group_store_df

In [7]:
group_store_df=purchase_df.groupby('store_id')

## Show the purchase transactions for store_id = G628, sorted from highest to lowest price

In [8]:
group_store_df.get_group('G628').sort_values(by = ['price'], inplace =False, ascending=False)

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
1565,10120,2015-01-08 21:26:00,G628,21000362,210301,1.0,5.000000
2422,10306,2015-08-13 00:37:00,G628,21000362,210301,3.0,5.000000
645,10331,2015-07-23 14:54:00,G628,21000362,210301,3.0,3.666667
26,10103,2015-07-15 20:06:00,G628,7308017,210101,1.0,3.500000
191,10165,2015-07-17 21:18:00,G628,7308017,210101,2.0,3.500000
...,...,...,...,...,...,...,...
2599,10233,2015-08-16 04:45:00,G628,7000300,210101,2.0,2.000000
2596,10197,2015-08-16 01:26:00,G628,7000300,210101,1.0,2.000000
2597,10208,2015-08-16 02:01:00,G628,7000300,210101,1.0,2.000000
2675,10250,2015-08-16 23:55:00,G628,7000126,210301,1.0,2.000000
2785,10296,2015-08-19 14:01:00,G628,7000300,210101,1.0,2.000000

## Show the average product price for each store.

In [9]:
group_store_df.price.mean()

store_id
G300     2.320946
G619     3.199972
G628     2.606803
G6666    2.220000
G816     3.253503
Name: price, dtype: float64