# Practice 3: Comsumption and Carbon footprints

In this set of practice exercises we’ll be again looking at the dataset of consumption and carbon footprints of different foods.

Importing pandas with the alias pd.

In [1]:
#Write your code here
import pandas as pd

Read the dataset as a dataframe named df from food_consumption.csv

In [2]:
#Write your code here
file_name = "food_consumption.csv"

try: 
    df = pd.read_csv(file_name, encoding='utf-8')
except FileNotFoundError as e1:
    print(f"File not found - {e1}")
except Exception as e2:
    print(f"Exception - {e2}")

What country consumes the most food per person per year (across all food categories)?

In [3]:
#Write your code here
df.groupby("country").sum().sort_values(by="consumption").tail(1)

,food_category,consumption,co2_emmission
country,,,
Finland,PorkPoultryBeefLamb & GoatFishEggsMilk - inc. ...,639.79,1464.63

Which food category is the biggest contributor to the above country’s consumption total?

In [4]:
#Write your code here
df.loc[df.country == 'Finland'].sort_values(by="consumption").tail(1)

     country       food_category  consumption  co2_emmission
149  Finland  Milk - inc. cheese       430.76         613.57

What country produces the most kg C02 per person per year?

In [5]:
#Write your code here
df.groupby("country").sum().sort_values(by="co2_emmission").tail(1)

,food_category,consumption,co2_emmission
country,,,
Argentina,PorkPoultryBeefLamb & GoatFishEggsMilk - inc. ...,429.41,2172.4

Which food category is the biggest contributor to the above country’s C02 emissions?

In [6]:
#Write your code here
df.loc[df.country == 'Argentina'].sort_values(by="co2_emmission").tail(1)

     country food_category  consumption  co2_emmission
2  Argentina          Beef        55.48         1712.0

What food category produces the most C02 per person per year across all countries?

In [7]:
#Write your code here
df.groupby("food_category").sum().sort_values(by="co2_emmission", ascending=False)

,country,consumption,co2_emmission
food_category,,,
Beef,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,1576.04,48633.26
Milk - inc. cheese,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,16350.71,23290.00
Lamb & Goat,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,338.02,11837.38
Pork,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,2096.08,7419.11
Rice,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,3818.77,4886.91
Fish,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,2247.32,3588.22
Poultry,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,2758.50,2963.16
Wheat and Wheat Products,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,9301.44,1773.78
Eggs,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,1061.29,974.95
Nuts inc. Peanut Butter,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,537.84,951.99
Soybeans,ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...,111.87,50.35

What food category is consumed the most across all countries per person per year? What food category is consumed the least across all countries?

In [8]:
#Write your code here
print("Most consumption:")
print(df.groupby("food_category").sum().sort_values(by="consumption", ascending=False).head(1))
print("")
print("Least consumption:")
print(df.groupby("food_category").sum().sort_values(by="consumption", ascending=False).tail(1))

Most consumption:
                                                              country  \
food_category
Milk - inc. cheese  ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...

                    consumption  co2_emmission
food_category
Milk - inc. cheese     16350.71        23290.0

Least consumption:
                                                         country  consumption  \
food_category
Soybeans       ArgentinaAustraliaAlbaniaIcelandNew ZealandUSA...       111.87

               co2_emmission
food_category
Soybeans               50.35

------------------------------------ End of Practice -----------------------------------------------